services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money-wizardry
    image: money-wizardry:latest
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    volumes:
      - .:/app
    env_file:
      - .env
    command: /bin/bash
    stdin_open: true
    tty: true
    networks:
      - money-wizardry-network
    depends_on:
      - db_postgres
      - redis

  db_postgres:
    image: postgres:latest
    container_name: money-wizardry-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - money-wizardry-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - db_postgres
    networks:
      - money-wizardry-network
    volumes:
      - ~/pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7-alpine
    container_name: fastapi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - money-wizardry-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --requirepass admin

volumes:
  postgres_data:
  redis_data:

networks:
  money-wizardry-network:
    driver: bridge